import {RedirectByDate} from "../interfaces/RedirectAnalytics";

//Houses Any utility function which can be used across the application.
export class CommonUtil {
    //Generated by Copilot to fill in missing dates in a series of RedirectByDate objects. #Shortcut
    static readonly fillMissingDates = (data: RedirectByDate[]): RedirectByDate[] => {
        if (data.length === 0) return [];
        debugger;
        // 1. Sort by date
        // const sorted = [...data].sort((a, b) => a.date.getDate() - b.date.getDate());
        const sorted = data;

        // 2. Build a quick lookup
        const lookup = new Map(sorted.map(item => [new Date(item.date).toDateString(), item]));

        const result: RedirectByDate[] = [];
        const current = new Date(sorted[0].date);
        const end = new Date(sorted[sorted.length - 1].date);

        // 3. Walk each day
        while (current <= end) {
            const key = current.toDateString();
            const entry = lookup.get(key);

            result.push(
                entry ?? { date: new Date(current), redirectCount: 0 }
            );

            current.setDate(current.getDate() + 1);
        }

        return result;
    };
}
